jQuery(document).ready(function(){
	jQuery("#select-menu-1").addClass('select-menu-hover');
	jQuery("#select-menu-1").hover(function(e){
		jQuery("#select-menu-4").removeClass('select-menu-hover');
		jQuery("#select-menu-3").removeClass('select-menu-hover');
		jQuery("#select-menu-2").removeClass('select-menu-hover');
		jQuery("#select-menu-1").addClass('select-menu-hover');
		jQuery("#img-menu-1").css("display","block");
		jQuery("#img-menu-2").css("display","none");
		jQuery("#img-menu-3").css("display","none");
		jQuery("#img-menu-4").css("display","none");
	});
	jQuery("#select-menu-2").hover(function(e){
		jQuery("#select-menu-1").removeClass('select-menu-hover');
		jQuery("#select-menu-4").removeClass('select-menu-hover');
		jQuery("#select-menu-3").removeClass('select-menu-hover');
		jQuery("#select-menu-2").addClass('select-menu-hover');
		jQuery("#img-menu-2").css("display","block");
		jQuery("#img-menu-1").css("display","none");
		jQuery("#img-menu-3").css("display","none");
		jQuery("#img-menu-4").css("display","none");
	});
	jQuery("#select-menu-3").hover(function(e){
		jQuery("#select-menu-1").removeClass('select-menu-hover');
		jQuery("#select-menu-2").removeClass('select-menu-hover');
		jQuery("#select-menu-4").removeClass('select-menu-hover');
		jQuery("#select-menu-3").addClass('select-menu-hover');
		jQuery("#img-menu-3").css("display","block");
		jQuery("#img-menu-2").css("display","none");
		jQuery("#img-menu-1").css("display","none");
		jQuery("#img-menu-4").css("display","none");
	});
	jQuery("#select-menu-4").hover(function(e){
		jQuery("#select-menu-1").removeClass('select-menu-hover');
		jQuery("#select-menu-2").removeClass('select-menu-hover');
		jQuery("#select-menu-3").removeClass('select-menu-hover');
		jQuery("#select-menu-4").addClass('select-menu-hover');
		jQuery("#img-menu-4").css("display","block");
		jQuery("#img-menu-2").css("display","none");
		jQuery("#img-menu-3").css("display","none");
		jQuery("#img-menu-1").css("display","none");
	});
});